version: 0.0
os: ubuntu
files: 
  - source: /
    destination: /home/ubuntu/healthlink
permissions:
  - object: /home/ubuntu/healthlink
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
      - location: scripts/clean_instance.sh
        timeout: 300
        runas: ubuntu
  AfterInstall:
      - location: scripts/instance_os_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/python_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/gunicorn.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/nginx.sh
        timeout: 300
        runas: ubuntu
  ApplicationStop:
      - location: scripts/stop_app.sh
        timeout: 300
        runas: ubuntu
  ApplicationStart:
      - location: scripts/start_app.sh
        timeout: 300
        runas: ubuntu
  
  