version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: config.settings.test
    SECRET_KEY: nosecret
    DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3
    DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
    STREAM_INCOMING_PRIVATE_KEY: changeme
    STREAM_INCOMING_PUBLIC_KEY: changeme
    GOOGLE_API_KEY: changeme
    OPBEAT_ENABLED: False

phases:
  pre_build:
    commands:
      - echo "Listing project directory contents:"
      - ls -al
      - echo "Contents of backend directory:"
      - ls -al backend
      - echo "Contents of requirements.txt file:"
      - cat backend/requirements.txt
      - pip3 install -r backend/requirements.txt  # Corrected path
      - chmod +x backend/buildspec.yml  # Grant execute permissions to the buildspec.yml file

  build:
    commands:
      - echo Building the application 

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
